AA_Master_fusion/12 Building Web Applications with Django/fidly/fidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

movie_resourse = MovieResource()

urlpatterns = [
    path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resourse.urls))
]

AA_Master_fusion/12 Building Web Applications with Django/fidly/movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:movie_id>", views.detail, name="detail")
]

AA_Master_fusion/12 Building Web Applications with Django/fidly/api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = "movies"
        excludes = ["date_created"]

# Create your models here.

AA_Master_fusion/12 Building Web Applications with Django/fidly/movies/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=255, unique=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255, unique=True)
    relase_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

AA_Master_fusion/12 Building Web Applications with Django/fidly/api/views.py
from django.shortcuts import render

# Create your views here.

AA_Master_fusion/12 Building Web Applications with Django/fidly/fidly/views.py
from django.shortcuts import render

def home(request):
    return render(request, "home.html")

AA_Master_fusion/12 Building Web Applications with Django/fidly/movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Movie

def index(request):
    movies = Movie.objects.all()
    return render(request, "movies/index.html", {"movies": movies})

def detail(request, movie_id):
        movie = get_object_or_404(Movie, pk=movie_id)
        return render(request, "movies/detail.html", {"movie": movie})

# Create your views here.

AA_Master_fusion/12 Building Web Applications with Django/fidly/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block content %}
    <dl>
        <dt>Title</dt>
        <dd>{{movie.title}}</dd>
        <dt>Genre</dt>
        <dd>{{movie.genre}}</dd>
        <dt>Year</dt>
        <dd>{{movie.relase_year}}</dd>
        <dt>Stock</dt>
        <dd>{{movie.number_in_stock}}</dd>
        <dt>Daily rate</dt>
        <dd>{{movie.daily_rate}}</dd>
    </dl>
{% endblock  %}

AA_Master_fusion/12 Building Web Applications with Django/fidly/movies/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Stock</th>
                <th>Daily Rate</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
                <tr>
                    <td>
                        <a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a>
                    </td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.number_in_stock }}</td>
                    <td>{{ movie.daily_rate }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

AA_Master_fusion/12 Building Web Applications with Django/fidly/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Fidly</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="#">Fidly</a>
    </nav>
    <main class="container">
      {% block content %}
      {% endblock %}
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

AA_Master_fusion/12 Building Web Applications with Django/fidly/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <a href={% url 'movies:index' %}>Movies</a>
{% endblock %}